---
- name: Terminate exsisting instance
  hosts: control
  connection: local  
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: absent
        instance_ids: "{{instanceid}}"
        region: us-east-1
        aws_access_key: "{{accessid}}"
        aws_secret_key: "{{secretid}}"
 
